cc_library(
    name = 'deeznesio',
    srcs = glob(['src/*.cpp', 'src/*.h']),
    hdrs = glob(['include/*.h']),
    include_prefix = "io",
    strip_include_prefix = "include",
    visibility = ["//visibility:public"],
)